# --- !Ups

CREATE TABLE ORGS (
   "O_ID" VARCHAR NOT NULL
  ,"NAME" VARCHAR NOT NULL
);
CREATE TABLE QUESTIONS (
   "Q_ID" VARCHAR NOT NULL
  ,"TEXT" VARCHAR NOT NULL
  ,"A1" VARCHAR NOT NULL
  ,"A2" VARCHAR NOT NULL
  ,"A3" VARCHAR NOT NULL
);
CREATE TABLE RESPONSES (
   "S_ID" VARCHAR NOT NULL
  ,"Q_ID" VARCHAR NOT NULL
  ,"U_ID" VARCHAR NOT NULL
  ,"O_ID" VARCHAR NOT NULL
  ,"RESPONSE" INT NOT NULL
  ,"TIMESTAMP" TIMESTAMP DEFAULT NOW()
);
CREATE TABLE SURVEYS   (
   "S_ID" VARCHAR NOT NULL
  ,"NAME" VARCHAR NOT NULL
);
CREATE TABLE SURVEY_QUESTIONS   (
   "S_ID" VARCHAR NOT NULL
  ,"Q_ID" VARCHAR NOT NULL
);
CREATE TABLE USER_ORGS   (
   "U_ID" VARCHAR NOT NULL
  ,"O_ID" VARCHAR NOT NULL
);

CREATE TABLE SECURITY   (
   "U_ID"   VARCHAR NOT NULL
  ,"HASHED" VARCHAR NOT NULL
  ,"ID"     VARCHAR NOT NULL
);

# --- !Downs

DROP TABLE ORGS;
DROP TABLE QUESTIONS;
DROP TABLE RESPONSES;
DROP TABLE SURVEYS;
DROP TABLE SURVEY_QUESTIONS;
DROP TABLE USER_ORGS;
DROP TABLE SECURITY;
